#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation

homepage:
  path: /
  defaults: { _controller: AppBundle:Default:index }

smarty_homepage:
  path: /smarty/
  defaults: { _controller: AppBundle:Default:smartyIndex }

request_querystring:
  path: /querystring/
  defaults: { _controller: AppBundle:Default:requestQuerystring }

request_post:
  path: /post/
  defaults: { _controller: AppBundle:Default:requestPost }
  methods: [POST]

calculator_index:
  path: /calculator/
  defaults: { _controller: AppBundle:Calculator:index }
  methods: [GET]

calculator_add:
  path: /calculator/add/
  defaults: { _controller: AppBundle:Calculator:add }
  methods: [POST]

xml:
  path: /xml/
  defaults: { _controller: AppBundle:Xml:index }

constraint:
  path: /{param}/
  defaults: { _controller: AppBundle:Default:paramConstraint }
  requirements:
    param: '\d+'

param_homepage:
  path: /{param}/
  defaults: { _controller: AppBundle:Default:param }