#app:
#    resource: "@ProductBundle/Controller/"
#    type:     annotation

product_create:
  path: /api/product/
  defaults: { _controller: \MyApp\Bundle\ProductBundle\Product\Api\Controller\CreateProductController::execute }
  methods: [POST]

product_delete:
  path: /api/product/{id}/
  defaults: { _controller: \MyApp\Bundle\ProductBundle\Product\Api\Controller\DeleteProductController::execute }
  methods: [DELETE]

product_update:
  path: /api/product/{id}/
  defaults: { _controller: \MyApp\Bundle\ProductBundle\Product\Api\Controller\UpdateProductController::execute }
  methods: [PUT]

product_list:
  path: /api/product/
  defaults: { _controller: \MyApp\Bundle\ProductBundle\Product\Api\Controller\ListProductsController::execute }
  methods: [GET]

owner_create:
  path: /api/owner/
  defaults: { _controller: \MyApp\Bundle\ProductBundle\Owner\Controller\CreateOwnerController::execute }
  methods: [POST]

owner_list:
  path: /api/owner/
  defaults: { _controller: \MyApp\Bundle\ProductBundle\Owner\Controller\ListOwnersController::execute }
  methods: [GET]

product_list_page:
  path: /{_locale}/product/
  defaults: { _controller: \MyApp\Bundle\ProductBundle\Product\Controller\ListProductsController::execute }
  methods: [GET]
  requirements:
    _locale: en|es
