#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation

#homepage:
#  path: /
#  defaults: { _controller: AppBundle:Default:index }
#
#constraint:
#  path: /{param}/
#  defaults: { _controller: AppBundle:Default:paramConstraint }
#  requirements:
#    param: '\d+'
#
#param_homepage:
#  path: /{param}/
#  defaults: { _controller: AppBundle:Default:param }

request_querystring:
  path: /querystring/
  defaults: { _controller: AppBundle:Default:requestQuerystring }

request_post:
  path: /post/
  defaults: { _controller: AppBundle:Default:requestPost }
  methods: [POST]

calculator_add:
  path: /add/{param1}/{param2}/
  defaults: { _controller: AppBundle:Calculator:add }
  methods: [POST]
  requirements:
    param1: '\d+'
    param2: '\d+'

calculator_subtract:
  path: /subtract/{param1}/
  defaults: { _controller: AppBundle:Calculator:subtract }
  methods: [POST]
  requirements:
    param1: '\d+'

calculator_multiply:
  path: /multiply/
  defaults: { _controller: AppBundle:Calculator:multiply }
  methods: [POST]

calculator_divide:
  path: /divide/{param1}/{param2}/
  defaults: { _controller: AppBundle:Calculator:divide }
  methods: [GET]
  requirements:
    param1: '\d+'
    param2: '\d+'