#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation

homepage:
  path: /
  defaults: { _controller: AppBundle:Default:index }

constraint:
  path: /{param}/
  defaults: { _controller: AppBundle:Default:paramConstraint }
  requirements:
    param: '\d+'

param_homepage:
  path: /{param}/
  defaults: { _controller: AppBundle:Default:param }

