# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
  my.twig.extension:
    class: MyApp\Bundle\AppBundle\Extensions\Twig\ClickMe
    tags:
      - { name: twig.extension }